language: node_js
node_js:
- '7'
script:
- yarn build
cache: yarn
addons:
  ssh_known_hosts: ssh.sizeme.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_0e9c5f5b7ff2_key -iv $encrypted_0e9c5f5b7ff2_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ ubuntu@ssh.sizeme.com:/opt/sizeme/instances/sizeme.js/qa/3.0
  on:
    branch: master