defaults: &defaults
  working_directory: ~/sizeme
  environment:
    TERM: dumb

yarnDeps: &yarnDeps
  keys:
    - v2-yarn-deps-{{ checksum "yarn.lock" }}
    - v2-yarn-deps-

yarnPaths: &yarnPaths
  paths:
    - node_modules
  key: v2-yarn-deps-{{ checksum "yarn.lock" }}

deploy: &deploy
  <<: *defaults

  docker:
    - image: sizeme/circleci-deploy:1.0

  steps:
    - attach_workspace:
        at: .

    - run:
        name: Move dist
        command: mv dist docker

    - deploy:
        name: Deploy client files
        command: >-
          aws s3 sync docker/dist/ s3://sizeme-bucket/store
          --exclude sizeme.js
          --cache-control max-age=31536000,public
          --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers &&
          aws s3 cp docker/dist/sizeme.js s3://sizeme-bucket/store/$SIZEME_REACT_ARTIFACT
          --cache-control public,must-revalidate,proxy-revalidate,max-age=0
          --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

version: 2

jobs:
  build:
    <<: *defaults

    docker:
      - image: circleci/node:11

    steps:
      - checkout

      - restore_cache:
          <<: *yarnDeps

      - run:
          name: Update dependencies
          command: cat /dev/null | yarn install

      - run:
          name: Build
          command: cat /dev/null | yarn build-cdn

      - persist_to_workspace:
          root: .
          paths:
            - docker
            - dist

      - save_cache:
          <<: *yarnPaths

  deploy_to_qa:
    <<: *deploy

  deploy_to_prod:
    <<: *deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*/
            branches:
              only: /.*/

      - deploy_to_qa:
          context: QA
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - add-crasman-kookenka-support

      - deploy_to_prod:
          context: PROD
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
